config/routes.rb
Rails.application.routes.draw do
  resources :investments
  resources :coins
  resources :global_parameters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'static_pages/home'

  #Root Page
  root to: 'static_pages#home'
end

app/models/investment.rb
class Investment < ApplicationRecord

	include CoinsHelper
	include ActionView::Helpers::NumberHelper
	require 'csv'

	validates_presence_of :balance, :currency

	has_many :coin_instances, dependent: :destroy

	after_save :create_coin_instances

	def create_coin_instances
		coins = Coin.all
		#We will get the exchange rates for the coins available in our application
		exchange_rates = get_all_coins_exchange_rates

		coins.each do |coin|
			#We will create a Coin Instance for each existing Coin record, for the purpose of this test there will be only 3 Coins available so the entire system is designed having this in mind, if there were many more possible Coins I would take another approach since it wouldn't be practical to generate so many records after every Investment made

			#We will by default handle everything with USD so we won't bother thinking about giving it a variable, we can just hard code it
			exchange_rate = exchange_rates.find{|r| r[:asset_id] == coin.code}

			#When exchange_rate isn't present, it means that the search had 0 matches which means that the API didn't return one of the Coins (ETH, BTC or ADA, usually ADA is the main culprit, since we do not have control over the API, we will just skip the missing coin)
			if exchange_rate.present?
				
				rate = exchange_rate[:price_usd]
				balance = self.balance
				coin_equivalent = calculate_coin_equivalent(self.balance, rate)
				anual_profit = calculate_anual_profit(balance, coin.monthly_interest)

				#Every record will be used as reference in case we want to check investments made previously, since crypto is so volatile, the prices change pretty often.

				#Another way of doing this would be to check via API while adding the timestamp but since it seems like the API sometimes doesn't return anything or just plainly returns nil, it might be safer to keep some records instead of relying so much on the API, just to be on the safer side
				coin_instance = self.coin_instances.create(
					coin_id: coin.id, 
					currency: self.currency,
					value_at_the_time: rate,
					coin_equivalent: coin_equivalent,
					anual_profit: anual_profit,
					total: balance + anual_profit
					)
			end

		end
		
	end

	def records_to_csv
		records = self.coin_instances
		CSV.generate do |csv|

			#We populate the CSV file with the headers
			csv << [
				"Coin",
				"Code",
				"Current Rate",
				"Monthly Interest (%)",
				"Interest (Yearly)",
				"Total"]

			#Now that we have the headers, we will populate it with the records data
			records.each do |r|
				csv << [
					r.coin.description,
					r.coin.code,
					number_to_currency(r.value_at_the_time, :unit => "$"),
					r.coin.monthly_interest,
					number_to_currency(r.anual_profit, :unit => "$"),
					number_to_currency(r.total, :unit => "$")
				]
			end
		end
	end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController

  include ActionView::Helpers::NumberHelper
  include CoinsHelper
  require 'roo'
  require 'json'

  before_action :set_investment, only: %i[ show edit update destroy download_as_csv]

  # GET /investments or /investments.json
  def index
    @investments = Investment.all
  end

  # GET /investments/1 or /investments/1.json
  def show
    @records = @investment.coin_instances
    tries = 0
    while @records.empty? && tries <= 3
      @investment.create_coin_instances
      @records = @investment.coin_instances
      tries += 1
      sleep 2
      puts "Failed Creating Coin Instances -- API ERROR"
    end

    respond_to do |format|
      format.html
      format.csv { send_data @investment.records_to_csv, filename: "investment_#{@investment.id}_exchange_rates_#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
      # json_data = @records.to_json(include: :investment)

      json_data = @records.to_json(include: {
        investment: {},
        coin: {}
      })
      format.json { send_data json_data, filename: "investment_#{@investment.id}_exchange_rates_#{DateTime.now.strftime("%d%m%Y%H%M")}.json" }      
    end
  end

  # GET /investments/new
  def new
    @investment = Investment.new
    @coins = Coin.all
    @exchange_rates = get_all_coins_exchange_rates
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments or /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to investment_path(@investment), notice: "Investment was successfully created." }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1 or /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to investment_url(@investment), notice: "Investment was successfully updated." }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1 or /investments/1.json
  def destroy
    @investment.destroy

    respond_to do |format|
      format.html { redirect_to investments_url, notice: "Investment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def investment_params
      params.require(:investment).permit(:balance, :currency)
    end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_coin_tables.html.haml
- if @exchange_rates.empty?
  .row.text-center.mt-5
    .col-12
      %h2
        CANNOT FETCH DATA FROM API - ERROR FROM API
- else
  %table.table.table-hover.table-striped.mt-5
    %thead
      %tr
        %th.text-left Coin
        %th.text-right Current Rate
        %th.text-center Monthly Interest
        / %th.text-right Interest (Yearly)
        / %th.text-right Total

    %tbody
      - @coins.each do |c|
        - exchange_rate = @exchange_rates.find{ |r|  r[:asset_id] == c.code}
        %tr
          %td.text-left
            - if c.code == "BTC"
              = image_tag("#{image_url('bitcoin.png')}", class: "img-responsive", style: "width: 30px; height: 30px;")
            - elsif c.code == "ETH"
              = image_tag("#{image_url('ethereum.png')}", class: "img-responsive", style: "width: 30px; height: 30px;")
            - else
              = image_tag("#{image_url('cardano.png')}", class: "img-responsive", style: "width: 30px; height: 30px;")
            = "#{c.description} (#{c.code})"
          %td.text-right
            %span.badge.badge-info 
              = number_to_currency(exchange_rate[:price_usd], :unit => "$")
          %td.text-center
            %span.badge.badge-dark
              = "#{c.monthly_interest} %"

app/views/investments/_form.html.haml
= simple_form_for @investment, defaults: { input_html: { class: 'form-control' } } do |f|

  = f.hidden_field :currency, value: "$" 
  .card.border-dark.text-center
    .card-body
      .row
        .offset-3.col-6
          = f.input :balance, placeholder: "Example: 100"

      %br
      .row
        .col-12
          = link_to 'Back', investments_path, class: "btn btn-primary"
          - if params[:action] != "show"
            = f.submit 'Invest!', class: "btn btn-primary"

app/views/investments/edit.html.haml
%h1 Editing investment

= render 'form'

= link_to 'Show', @investment
\|
= link_to 'Back', investments_path

app/views/investments/index.html.haml
.row.text-center
  .col-12
    %h1 Investments Records

%table.table.table-hover.table-striped
  %thead
    %tr
      %th.text-center ID
      %th.text-center Currency
      %th.text-right Balance
      %th.text-center Options

  %tbody
    - @investments.each do |investment|
      %tr
        %td.text-center
          = investment.id
        %td.text-center
          %h3
            %span.badge.badge-success
              = investment.currency
        %td.text-right
          %h3
            %span.badge.badge-success
              = number_to_currency(investment.balance, :unit => "$")
        %td.text-center
          = link_to "Show", investment, class: "btn btn-primary"

app/views/investments/new.html.haml
.text-center
	%h1 New Investment

= render 'form'

= render 'coin_tables'

app/views/investments/show.html.haml
- if notice.present?
  .alert.alert-success{role: "alert"}
    = notice
.row.text-center
  .col-12
    %a.btn.btn-primary.btn-lg{href: new_investment_path, role: "button"} Make Another Investesment!
%hr
.row.text-center.mt-5
  / .col-12
  /   %h1
  /     %b 
  /       = "Balance: #{number_to_currency(@investment.balance, :unit => "$")}"
  .col-12
    .card.text-center
      .card-header
        %h4
          %b
            Balance
      .card-body
        %h1.card-title  
          = "#{number_to_currency(@investment.balance, :unit => "$")}"
      .card-footer.text-muted
        = "Current Rates as of: #{@investment.created_at.strftime("%d-%m-%Y %H:%M:%S")}"
%hr
/ .row.text-center
/   .col-12
/     %h5
/       = "Current Rates as of: #{@investment.created_at.strftime("%d-%m-%Y %H:%M:%S")}"
%br

- if @records.empty?
  .row.text-center
    .col-12
      %h2
        CoinAPI isn't working, please refresh this page later
- else
  .row.text-right
    .col-12
      / = link_to "Download as CSV", download_as_csv_investment_path(@investment)
      / = link_to 'Download CSV Report', download_as_csv_investment_path(@investment, format: :csv), class: 'btn btn-primary'
      = link_to 'Download CSV Report', investment_path(@investment, format: 'csv'), class: 'btn btn-primary'
      = link_to 'Download JSON Report', investment_path(@investment, format: 'json'), target: "_blank", class: 'btn btn-primary'
  %br
  %table.table.table-hover.table-striped
    %thead
      %tr
        %th.text-left Coin
        %th.text-right Current Rate
        %th.text-center Monthly Interest
        %th.text-right Interest (Yearly)
        %th.text-right Total

    %tbody
      - @investment.coin_instances.each do |ci|
        %tr
          %td.text-left
            - if ci.coin.code == "BTC"
              = image_tag("#{image_url('bitcoin.png')}", class: "img-responsive", style: "width: 30px; height: 30px;")
            - elsif ci.coin.code == "ETH"
              = image_tag("#{image_url('ethereum.png')}", class: "img-responsive", style: "width: 30px; height: 30px;")
            - else
              = image_tag("#{image_url('cardano.png')}", class: "img-responsive", style: "width: 30px; height: 30px;")
            = "#{ci.coin.description} (#{ci.coin.code})"
          %td.text-right
            %span.badge.badge-info{id: "current_rate"}
              = number_to_currency(ci.value_at_the_time, :unit => "$")
          %td.text-center
            %span.badge.badge-dark
              = "#{ci.coin.monthly_interest} %"
          %td.text-right
            %span.badge.badge-success 
              = number_to_currency(ci.anual_profit, :unit => "$")
          %td.text-right
            %span.badge.badge-success 
              = number_to_currency(ci.total, :unit => "$")