config/routes.rb
Rails.application.routes.draw do
  resources :investments
  resources :coins
  resources :global_parameters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'static_pages/home'

  #Root Page
  root to: 'static_pages#home'
end

app/models/global_parameter.rb
class GlobalParameter < ApplicationRecord
end

app/controllers/global_parameters_controller.rb
class GlobalParametersController < ApplicationController
  before_action :set_global_parameter, only: %i[ show edit update destroy ]

  # GET /global_parameters or /global_parameters.json
  def index
    @global_parameters = GlobalParameter.all
  end

  # GET /global_parameters/1 or /global_parameters/1.json
  def show
  end

  # GET /global_parameters/new
  def new
    @global_parameter = GlobalParameter.new
  end

  # GET /global_parameters/1/edit
  def edit
  end

  # POST /global_parameters or /global_parameters.json
  def create
    @global_parameter = GlobalParameter.new(global_parameter_params)

    respond_to do |format|
      if @global_parameter.save
        format.html { redirect_to global_parameter_url(@global_parameter), notice: "Global parameter was successfully created." }
        format.json { render :show, status: :created, location: @global_parameter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @global_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /global_parameters/1 or /global_parameters/1.json
  def update
    respond_to do |format|
      if @global_parameter.update(global_parameter_params)
        format.html { redirect_to global_parameter_url(@global_parameter), notice: "Global parameter was successfully updated." }
        format.json { render :show, status: :ok, location: @global_parameter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @global_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /global_parameters/1 or /global_parameters/1.json
  def destroy
    @global_parameter.destroy

    respond_to do |format|
      format.html { redirect_to global_parameters_url, notice: "Global parameter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_global_parameter
      @global_parameter = GlobalParameter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def global_parameter_params
      params.require(:global_parameter).permit(:description, :code)
    end
end

app/helpers/global_parameters_helper.rb
module GlobalParametersHelper
end

app/views/global_parameters/_form.html.haml
= form_for @global_parameter do |f|
  - if @global_parameter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@global_parameter.errors.count, "error")} prohibited this global_parameter from being saved:"
      %ul
        - @global_parameter.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :code
    = f.text_field :code
  .actions
    = f.submit 'Save'

app/views/global_parameters/edit.html.haml
%h1 Editing global_parameter

= render 'form'

= link_to 'Show', @global_parameter
\|
= link_to 'Back', global_parameters_path

app/views/global_parameters/index.html.haml
%h1 Listing global_parameters

%table
  %thead
    %tr
      %th Description
      %th Code
      %th
      %th
      %th

  %tbody
    - @global_parameters.each do |global_parameter|
      %tr
        %td= global_parameter.description
        %td= global_parameter.code
        %td= link_to 'Show', global_parameter
        %td= link_to 'Edit', edit_global_parameter_path(global_parameter)
        %td= link_to 'Destroy', global_parameter, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Global parameter', new_global_parameter_path

app/views/global_parameters/new.html.haml
%h1 New global_parameter

= render 'form'

= link_to 'Back', global_parameters_path

app/views/global_parameters/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @global_parameter.description
%p
  %b Code:
  = @global_parameter.code

= link_to 'Edit', edit_global_parameter_path(@global_parameter)
\|
= link_to 'Back', global_parameters_path