config/routes.rb
Rails.application.routes.draw do
  resources :investments
  resources :coins
  resources :global_parameters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'static_pages/home'

  #Root Page
  root to: 'static_pages#home'
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :code, :monthly_interest)
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
	def initiate_coin_api
		api = CoinapiV1::Client.new(api_key: GlobalParameter.find_by(code: "coinapi").value)
	end

	def calculate_coin_equivalent(investment, coin_rate)
		return equivalent = investment / coin_rate
	end

	def calculate_anual_profit(investment, coin_interest)
		(investment * (coin_interest / 100) )
	end

	def get_all_coins_exchange_rates
		api = initiate_coin_api
		coins = Coin.all

		exchange_rates = []

		### At first I was getting all 3 coins one by one using the exchange_rates_get_specific_rate but since it seems like there is an API limit and that is causing some errors because its returning nil, I am going to use the method that gives me all the coins and i will filter them myself

		# coins.each do |coin|
		# 	not_created = true
		# 	tries = 0
		# 	while not_created && tries < 3

		# 		begin
		# 			sleep 1
		# 			exchange_rates << exchange_rate = api.exchange_rates_get_specific_rate(asset_id_base: coin.code, asset_id_quote: 'USD')
		# 			not_created = false
		# 		rescue
		# 			tries += 1
		# 			puts "API Error - Coin Code: #{coin.code}"
		# 		end
		# 	end
		# end

		begin
			results = api.metadata_list_all_assets
			coins.pluck(:code).each do |coin|
				results.find { |r| exchange_rates << r if r[:asset_id] == coin } 
			end
		rescue
			puts "API ERROR"
		end

		return exchange_rates
	end
end

app/views/coins/_form.html.haml
= form_for @coin do |f|
  - if @coin.errors.any?
    #error_explanation
      %h2= "#{pluralize(@coin.errors.count, "error")} prohibited this coin from being saved:"
      %ul
        - @coin.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :monthly_interest
    = f.text_field :monthly_interest
  .actions
    = f.submit 'Save'

app/views/coins/edit.html.haml
%h1 Editing coin

= render 'form'

= link_to 'Show', @coin
\|
= link_to 'Back', coins_path

app/views/coins/index.html.haml
%h1 Listing coins

%table
  %thead
    %tr
      %th Description
      %th Code
      %th Monthly interest
      %th
      %th
      %th

  %tbody
    - @coins.each do |coin|
      %tr
        %td= coin.description
        %td= coin.code
        %td= coin.monthly_interest
        %td= link_to 'Show', coin
        %td= link_to 'Edit', edit_coin_path(coin)
        %td= link_to 'Destroy', coin, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Coin', new_coin_path

app/views/coins/new.html.haml
%h1 New coin

= render 'form'

= link_to 'Back', coins_path

app/views/coins/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @coin.description
%p
  %b Code:
  = @coin.code
%p
  %b Monthly interest:
  = @coin.monthly_interest

= link_to 'Edit', edit_coin_path(@coin)
\|
= link_to 'Back', coins_path